### ISSUE TITLE
Settings handling error on split if empty or incorrect value.

### ISSUE THREAD

**Issue by alienigenagamer** [sync667/UseTS-AdminBOT#1]
Error running JS-Wrap: TypeError: Cannot access member 'split' of undefined at _script__se___dmin____js (<anonymous>:13:48) at ScriptRunner (<anonymous>:191:4) at <unknown>

**Comment by sync667** [comment]
Please add your configuration of script and full log of instance. Before you should try to turn off script and check if error still occurs. If no it's not related with our script.

**Comment by sync667** [comment]
I was checking this with another user and found solution. I will handle errors on that split codes if no value is typed or it's incorrect. So in next update users won't have that problems.

**Comment by sync667** [comment]
Bug fixed - new release https://github.com/sync667/UseTS-AdminBOT/releases/tag/0.3.3
