### ISSUE TITLE
Nie działa Rekord online

### ISSUE THREAD

**Issue by Hakens** [sync667/UseTS-AdminBOT#10]
Tak jak pisałem na forum sinusbota dołączam instance log i screen ustawień
[instance log.txt](https://github.com/sync667/UseTS-AdminBOT/files/228738/instance.log.txt)
![ustawienia](https://cloud.githubusercontent.com/assets/18582346/14688861/fa059582-0744-11e6-9f25-76cb90120316.png)

**Comment by sync667** [comment]
Pobierz proszę kod nowej wersji pliku skryptu i daj znać, czy liczba się zaktualizowała.

**Comment by Hakens** [comment]
Takie coś w ssh wyskakuje nie wiem czy to wina tego pluginu ale wczesniej tego nie widzialem
![bez tytulu](https://cloud.githubusercontent.com/assets/18582346/14715839/b7560216-07ea-11e6-8c6a-d1ec265a20a5.png)
Myślę ze to wina w tych linijkach search jest nie zdefiniowane
![bez tytulu](https://cloud.githubusercontent.com/assets/18582346/14715902/039e04a2-07eb-11e6-8285-f73a9bf23105.png)

]Ps. z jakiego programu korzystasz pisząc skrypty do sinusbota?

**Comment by sync667** [comment]
Faktycznie moja wina, ale powinno działać, bo funkcja jest standardowa JS. Sprawdzę to i wyślę poprawkę.

**Comment by sync667** [comment]
PS: Ja pracuję na InteliJ.

**Comment by sync667** [comment]
Sprawdziłeś ostatnie zmiany?

**Comment by Hakens** [comment]
Wywala takie cos w logu i dalej nie dziala rekord online 
![blad](https://cloud.githubusercontent.com/assets/18582346/14858867/006a54fa-0ca2-11e6-85b7-2d2c4f9ee467.png)

**Comment by sync667** [comment]
W weekend zajmę się tym dokładniej, bo tak nie mam za bardzo jak testować zmian.
