### ISSUE TITLE
Bot doesnt delete temp channels

### ISSUE THREAD

**Issue by jksimmi** [sync667/UseTS-AdminBOT#11]
Hi, for me the bot doesnt delete the temp channels, it just logs 

> TypeError: Cannot access member 'clients' of undefined at getClientsNumber (<anonymous>:836:29) at <anonymous>:356:21

in the Instance log. Im using **SinusBot 0.9.11-d20ec68** and **TS-AdminBOT 0.3.5**

i gave the bot Server Query Admin to check if he misses any permission, same error =(

sorry for my bad English
p.s.
im using a 64bit Debian Vserver on my Proxmox Host 
musicbot@teamspeak ~$ uname -a
Linux teamspeak 2.6.32-44-pve #1 SMP Sun Mar 13 17:00:54 CET 2016 x86_64 GNU/Linux

**Comment by sync667** [comment]
Can you please paste whole log within place where error occurred?

**Comment by jksimmi** [comment]
sure, im reinstalling sinusbot atm. give me 10 minutes please :>

**Comment by jksimmi** [comment]
it seems to be a problem with the operating system. 
with another virtual server instance its working flawless.
im trying to figure out the problem, if i find the problem i'll let you know (i have not deleted the vserver container).
