### ISSUE TITLE
Registation Group ID

### ISSUE THREAD

**Issue by ghost** [sync667/UseTS-AdminBOT#18]
It would be very nice, if you can type more than 1 registration group id!
So that the bot can pokes/write also only one group as welcome message.
(I have following groups: Admin, Mod, Designer, YouTube, VIP, Member and Guest. And i want that only the guests get an message or poke (by joining server) that they have to register on my website to get member)

It would be very nice if you include this feature :+1: :)

**Comment by sync667** [comment]
Will add this on TODO list.

**Comment by ghost** [comment]
Cool! This feature will help me a lot! :)
