### ISSUE TITLE
AI don't reply to users every time

### ISSUE THREAD

**Issue by zanhk** [sync667/UseTS-AdminBOT#4]
AI reply to users every 3-4 messages and don't at the first time.
Also if i think this is a problem of Online AI service and not of the script.

**Comment by sync667** [comment]
AI of bots is very experimental function and need much improvement for like you say Online AI service side. I will be improving that, but not to fast till i have much more important functions to do. AI is very complex so much work to do and i don't have time for that now.

Basically this is not as much redundant as is want. Problems come when many users use it at the same time and it's not server or network performance issue, but script and service that is used to handle AI.
