### ISSUE TITLE
Support Function issue

### ISSUE THREAD

**Issue by zanhk** [sync667/UseTS-AdminBOT#5]
The Support Function don't recognize all registered Groups ID's from the camp "Support Members - GroupsID (comma separated)", i don't know if is just for me but it takes only the first one.
Bad formattation? (**9,10,12**) (i have also tried **9, 10, 12** but doesn't work too).
Sorry for bad english
-ZanK

**Comment by sync667** [comment]
!Important - Because of Sinusbot group loading function that is fixed in future versions Script can't sometimes discover users groups on server properly.
