### ISSUE TITLE
[Function: Support Members - GroupsIDs] does not parse multiple group IDs

### ISSUE THREAD

**Issue by pix0wl** [sync667/UseTS-AdminBOT#7]
Hi, 

I've added my admin and moderator groups, but only the first group (6) will be identified and used.

Support Members - GroupsID (comma separated)
`6,11,18`
Group ignored on support channels - GroupsID (comma separated)
`6,11,18`

**Comment by sync667** [comment]
You done restart after settings change and wait about 30 seconds to minute? At it still don't resolve groups right? Please check it.

Check too if you don't get any errors in instance logs so parsing would be break.

**Comment by pix0wl** [comment]
Yes, I've had restarted the bot. Also it was my first setup, I've didn't change the values afterwards.

Edit: I was a little too quick... It is is working. The clients who are online at the moment the function is activated are just not counted, they have to rejoin the server.
Sorry, I will next time check more carefully.

**Comment by sync667** [comment]
Can you send me your full configuration?

**Comment by pix0wl** [comment]
config.ini:
`
TS3Path = "/home/*********_/TeamSpeak3-Client-linux_amd64/ts3client_linux_amd64"
ListenHost = "0.0.0.0"
DataDir = "/home/**_******_/data/"
ListenPort = 8087
LocalPlayback = false
EnableLocalFS = false
MaxBulkOperations = 300
LogLevel = 3
EnableProfiler = false
YoutubeDLPath = "/usr/local/bin/youtube-dl"
EnableDebugConsole = false
UploadLimit = 83886080
RunAsUser = 0
RunAsGroup = 0
InstanceActionLimit = 6
UseSSL = false
SSLKeyFile = ""
SSLCertFile = ""
Hostname = ""
SampleInterval = 140
StartVNC = false
EnableWebStream = false
LogFile = ""
LicenseKey = "**_*************************************"
DisableLocalXServer = false
DebugLocalXServer = false
IsProxied = false
DenyStreamURLs = []
Pragma = 0

[YoutubeDL]
  BufferSize = 524288
  MaxDownloadSize = 419430400
  MaxDownloadRate = 104857600
  CacheStreamed = false

[TS3]
  AvatarMaxWidth = 0
  AvatarMaxHeight = 0

[StreamRewrites]

[Scripts]
  AllowReload = true
  EnableTimer = true

[SpeechRecognition]
  Enable = false

[FFmpeg]
  UserAgent = "SinusBot (0.9.11-ee30ef7)"

[DAV]
  Enable = false
`
script config:
http://i.imgur.com/AQhc8OO.png

**Comment by sync667** [comment]
Yea that's right clients must not rejoin, but just move on channels to be counted after restart or settings change.
