### ISSUE TITLE
Distortion after event

### ISSUE THREAD

**Issue by jKemmkey** [sync667/UseTS-AdminBOT#8]
Hello. When users join server, hop from channel to channel or disconnect from server (everything that creates a log) if you are listening to the bot, you can clearly hear audio distortion sounds. After event has registered it streams correcty

**Comment by sync667** [comment]
Hi, maybe Sinusbot have performance issue with that, but i will check this. How much users you have on server average?

**Comment by jKemmkey** [comment]
25 users average. Checked also with 2 users inside and same problem.

**Comment by sync667** [comment]
Can you record that for me? I have about 100 users average and nothing like that happen.

**Comment by jKemmkey** [comment]
There you go. Distortions happened when user joined server, when bot sent him a welcome message, when user hopped on multiple channels and when he quit the server.
[Recording.zip](https://github.com/sync667/UseTS-AdminBOT/files/211729/Recording.zip)

**Comment by sync667** [comment]
I think that is very occasional bug, but like i think it's because of sinusbot. Last internal version have something in changelog about that "Again, most changes have been made under the hood and should reduce occasional lagging / stuttering caused by scripts." so it will be fixed soon when sinusbot will release new Beta.

**Comment by jKemmkey** [comment]
I'm running the latest beta version. Btw i had to torn off your script, because of that. I hope it will work again in the future. Thanks again

**Comment by sync667** [comment]
Internal versions are not Beta ;) This are versions that are available only for special group of people on Sinusbot. But of course i will try to optimize code to prevent this and this won't be easy.
