### ISSUE TITLE
Bot AI not working

### ISSUE THREAD

**Issue by chris100184** [sync667/UseTS-AdminBOT#9]
I recently ran into some problems with my vps and had to reinstall everything. and now after i've setup everything like before. i can't seem to get the AI (chat reply) to work. i've only gotten the reply to pokes semi working, where it would send a poke back, but with no reply. I'm not able to find anything in the log files. so yeah.

**Comment by chris100184** [comment]
so after editing config.ini for sinusbot i was able to find something in the log

`
2016-04-10T15:05:48+02:00 GEThttps://usets.pl/bot.php?msg=hi<nil>
2016-04-10T15:05:48+02:00 PRIVATE-CHAT [Chris] hi
`

**Comment by sync667** [comment]
Hello, please check it right know, because we had changed servers that handle bot AI and it was not available some time.
